// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
// /// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOztNmqJIsSdB96WbzcNvpyRf3ydut-XQ',
    appId: '1:75153274012:web:959f52c33508929557e959',
    messagingSenderId: '75153274012',
    projectId: 'e-commerce-app-fa62e',
    authDomain: 'e-commerce-app-fa62e.firebaseapp.com',
    storageBucket: 'e-commerce-app-fa62e.firebasestorage.app',
    measurementId: 'G-TFN4TP4N6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_RkUYNAFRlB4BOANq5Padi1LJ_ZlNOnQ',
    appId: '1:75153274012:android:20d17acc567e258a57e959',
    messagingSenderId: '75153274012',
    projectId: 'e-commerce-app-fa62e',
    storageBucket: 'e-commerce-app-fa62e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpmWPuguDRTLWem8p1T3ZOF9jMNqAZOjo',
    appId: '1:75153274012:ios:3ec95225c6cf29bb57e959',
    messagingSenderId: '75153274012',
    projectId: 'e-commerce-app-fa62e',
    storageBucket: 'e-commerce-app-fa62e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpmWPuguDRTLWem8p1T3ZOF9jMNqAZOjo',
    appId: '1:75153274012:ios:3ec95225c6cf29bb57e959',
    messagingSenderId: '75153274012',
    projectId: 'e-commerce-app-fa62e',
    storageBucket: 'e-commerce-app-fa62e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOztNmqJIsSdB96WbzcNvpyRf3ydut-XQ',
    appId: '1:75153274012:web:61e2ceff8ae5df8d57e959',
    messagingSenderId: '75153274012',
    projectId: 'e-commerce-app-fa62e',
    authDomain: 'e-commerce-app-fa62e.firebaseapp.com',
    storageBucket: 'e-commerce-app-fa62e.firebasestorage.app',
    measurementId: 'G-CETHE8R9SE',
  );
}
